### ISSUE TITLE
Failed to patch with null, error: TypeError: data.map is not a function at mapIds

### ISSUE THREAD

**Issue by sinonkt** [feathersjs-ecosystem/feathers-mongoose#289]
### Steps to reproduce
fail to patch with mongoose `upsert` which once ever worked on v6.3.0 but failed at v7.1.1
``` 
 const taskParams = {
   query: { runId: data.runId, task_id: taskTrace.task_id },
   mongoose: { upsert: true, writeResult: true },
 };

this.app.service('tasks').patch(null, { runId: data.runId, ...taskTrace }, taskParams);
```
```
service({ multi: [ 'patch'] })
```
### Expected behavior
this worked fine on version 6.3.0

### Actual behavior
```
error: TypeError: data.map is not a function
at mapIds (/home/app/node_modules/feathers-mongoose/lib/service.js:208:33)
at process.internalTickCallback (internal/process/next_tick.js:77:7)
error: Unhandled Rejection at: Promise  {"meta":[{},{}]}`enter code here`
```

### System configuration

**Module versions** : v7.1.1

**NodeJS version**: v11.6.0

**Operating System**: macOS

**Comment by daffl** [comment]
This is being tested in https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/master/test/index.test.js#L348 and I am not able to reproduce the issue. Do you have a complete breaking example?

**Comment by daffl** [comment]
Like I said, there isn't much to suggest without more information. The tests for a request like that are passing successfully so it must be something else in your service configurations that is different. `raw: false`? Application level hooks? Pagination on/off? Gremlins?

**Comment by apmcodes** [comment]
Understand. Thanks for the reply.

**lists.service.js**
```
const createService = require('feathers-mongoose');
const Model = require('../../models/lists.model');
const hooks = require('./lists.hooks');

module.exports = function (app) {
    const paginate = app.get('paginate');
    const options = {
        id: 'ListId',
        Model,
        paginate,
        multi: true,
        lean: true,
    };

    // Initialize our service with any options it requires
    app.use('/lists', createService(options));

    // Get our initialized service so that we can register hooks
    const service = app.service('lists');

    service.hooks(hooks);
};

```
**default.json***
```
    "paginate": {
        "default": 10,
        "max": 50
    },
```

**app hooks**
```
all: [log()],
```
Tried both raw:false and true ... same error

Please let me know if need to look at any other places...

**Comment by daffl** [comment]
Should be fixed in v7.1.3
